import { miTaxonomyVersion } from '../../config/mi/taxonomy';
import { MiClinicalGroup, MiEvidenceDomain, MiScenarioCase } from '../../types/mi/classification';

const at = (hour: number, minute = 0) => `2026-10-04T${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}:00Z`;
const evidence = (id: string, domain: MiEvidenceDomain, state: 'PRESENT' | 'ABSENT' | 'INDETERMINATE' | 'NOT_OBSERVED', observedAt: string, summary: string, limitations: readonly string[] = []) => ({ id, domain, state, observedAt, summary, provenance: 'SIMULATED' as const, limitations });
const event = (id: string, hour: number, domain: MiEvidenceDomain, title: string, detail: string, evidenceIds: readonly string[]) => ({ id, occurredAt: at(hour), domain, title, detail, evidenceIds });

const scenario = (input: Omit<MiScenarioCase, 'scenarioPackId' | 'taxonomyVersion' | 'provenance'>): MiScenarioCase => ({
  ...input, scenarioPackId: 'full-mi-spectrum-core-v1', taxonomyVersion: miTaxonomyVersion, provenance: 'SIMULATED',
});

export const miScenarios: readonly MiScenarioCase[] = [
  scenario({
    id: 'primary-stemi', title: 'Primary MI · ST-elevation presentation', learningObjective: 'Explore convergent symptom, ECG, troponin, and coronary evidence.', descriptors: ['Anterior territory', 'Acute coronary pathology pattern'],
    evidence: [evidence('s1', 'SYMPTOMS', 'PRESENT', at(8), 'New simulated pressure-like chest discomfort.'), evidence('e1', 'ECG', 'PRESENT', at(8, 10), 'Simulated new ST-segment elevation pattern.'), evidence('t1', 'TROPONIN', 'PRESENT', at(9), 'Simulated rise above assay reference limit.'), evidence('a1', 'ANGIOGRAPHY', 'PRESENT', at(10), 'Simulated acute thrombotic coronary finding.'), evidence('i1', 'IMAGING', 'PRESENT', at(10, 20), 'Simulated new regional wall-motion abnormality.')],
    timeline: [event('ev1', 8, 'SYMPTOMS', 'Symptoms recorded', 'Simulated symptom onset entered.', ['s1']), event('ev2', 8, 'ECG', 'ECG evidence', 'ST-elevation presentation label recorded.', ['e1']), event('ev3', 9, 'TROPONIN', 'Serial biomarker', 'Rise shown in simulated series.', ['t1']), event('ev4', 10, 'ANGIOGRAPHY', 'Coronary context', 'Thrombotic finding recorded in scenario.', ['a1'])],
    troponinSeries: [{ occurredAt: at(8), value: 14, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(9), value: 84, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(10), value: 430, unit: 'ng/L', upperReferenceLimit: 14 }],
    expectedAssessment: { category: 'PRIMARY', legacyType: 'TYPE_1', presentation: 'STEMI', label: 'Primary MI pattern', confidence: 'SUPPORTED', explanation: 'Multiple simulated evidence domains converge on acute coronary pathology.', supportingEvidenceIds: ['s1', 'e1', 't1', 'a1', 'i1'], conflictingEvidenceIds: [], evidenceGaps: [], disclaimer: 'SIMULATION_ONLY' },
  }),
  scenario({
    id: 'primary-nstemi', title: 'Primary MI · Non-ST-elevation presentation', learningObjective: 'Compare a primary pattern without ST-elevation presentation.', descriptors: ['Inferior territory', 'Non-ST-elevation presentation'],
    evidence: [evidence('s2', 'SYMPTOMS', 'PRESENT', at(8), 'Simulated ischaemic symptoms.'), evidence('e2', 'ECG', 'PRESENT', at(8, 15), 'Simulated ischaemic ST/T-wave changes without ST elevation.'), evidence('t2', 'TROPONIN', 'PRESENT', at(9), 'Simulated dynamic troponin rise.'), evidence('a2', 'ANGIOGRAPHY', 'PRESENT', at(11), 'Simulated plaque disruption with non-occlusive thrombus.')],
    timeline: [event('ev5', 8, 'SYMPTOMS', 'Symptoms recorded', 'Simulated onset.', ['s2']), event('ev6', 8, 'ECG', 'ECG evidence', 'Non-ST-elevation pattern recorded.', ['e2']), event('ev7', 9, 'TROPONIN', 'Serial biomarker', 'Dynamic rise recorded.', ['t2']), event('ev8', 11, 'ANGIOGRAPHY', 'Coronary context', 'Non-occlusive thrombus recorded.', ['a2'])],
    troponinSeries: [{ occurredAt: at(8), value: 11, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(9), value: 59, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(11), value: 205, unit: 'ng/L', upperReferenceLimit: 14 }],
    expectedAssessment: { category: 'PRIMARY', legacyType: 'TYPE_1', presentation: 'NSTEMI', label: 'Primary MI pattern', confidence: 'SUPPORTED', explanation: 'The simulation pairs dynamic injury evidence with a coronary pathology pattern.', supportingEvidenceIds: ['s2', 'e2', 't2', 'a2'], conflictingEvidenceIds: [], evidenceGaps: [], disclaimer: 'SIMULATION_ONLY' },
  }),
  scenario({
    id: 'secondary-supply-demand', title: 'Secondary MI · Supply–demand imbalance', learningObjective: 'Distinguish simulated supply–demand context from plaque-disruption context.', descriptors: ['Tachyarrhythmia context', 'No plaque disruption simulated'],
    evidence: [evidence('c3', 'CONTEXT', 'PRESENT', at(8), 'Simulated sustained tachyarrhythmia and hypotension context.'), evidence('t3', 'TROPONIN', 'PRESENT', at(9), 'Simulated dynamic troponin rise.'), evidence('e3', 'ECG', 'PRESENT', at(9), 'Simulated transient ischaemic changes.'), evidence('a3', 'ANGIOGRAPHY', 'ABSENT', at(11), 'No simulated acute atherothrombotic finding.')],
    timeline: [event('ev9', 8, 'CONTEXT', 'Acute context', 'Supply–demand stressor recorded.', ['c3']), event('ev10', 9, 'TROPONIN', 'Serial biomarker', 'Rise recorded.', ['t3']), event('ev11', 11, 'ANGIOGRAPHY', 'Coronary context', 'No acute atherothrombosis in scenario.', ['a3'])],
    troponinSeries: [{ occurredAt: at(8), value: 15, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(9), value: 76, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(11), value: 122, unit: 'ng/L', upperReferenceLimit: 14 }],
    expectedAssessment: { category: 'SECONDARY', legacyType: 'TYPE_2', presentation: 'NSTEMI', label: 'Secondary MI pattern', confidence: 'SUPPORTED', explanation: 'The simulation indicates injury and ischaemia in a supply–demand context without plaque disruption.', supportingEvidenceIds: ['c3', 't3', 'e3', 'a3'], conflictingEvidenceIds: [], evidenceGaps: [], disclaimer: 'SIMULATION_ONLY' },
  }),
  scenario({
    id: 'procedure-pci', title: 'Procedure-related MI · PCI context', learningObjective: 'Review simulated post-PCI evidence and timing.', descriptors: ['PCI context', 'Legacy 4a label'],
    evidence: [evidence('p4', 'PROCEDURE', 'PRESENT', at(8), 'Simulated PCI with a recorded procedural complication.'), evidence('t4', 'TROPONIN', 'PRESENT', at(10), 'Simulated post-procedure biomarker increase.'), evidence('i4', 'IMAGING', 'PRESENT', at(10, 20), 'Simulated new regional wall-motion finding.'), evidence('e4', 'ECG', 'PRESENT', at(10), 'Simulated new ischaemic ECG change.')],
    timeline: [event('ev12', 8, 'PROCEDURE', 'PCI recorded', 'Procedure context begins timeline.', ['p4']), event('ev13', 10, 'TROPONIN', 'Post-procedure biomarker', 'Increase recorded.', ['t4']), event('ev14', 10, 'ECG', 'ECG evidence', 'New simulated change recorded.', ['e4'])],
    troponinSeries: [{ occurredAt: at(8), value: 12, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(10), value: 92, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(12), value: 180, unit: 'ng/L', upperReferenceLimit: 14 }],
    expectedAssessment: { category: 'PROCEDURE_RELATED', legacyType: 'TYPE_4A', presentation: 'UNKNOWN', label: 'Procedure-related MI pattern', confidence: 'SUPPORTED', explanation: 'The simulation aligns new evidence with documented PCI context.', supportingEvidenceIds: ['p4', 't4', 'i4', 'e4'], conflictingEvidenceIds: [], evidenceGaps: [], disclaimer: 'SIMULATION_ONLY' },
  }),
  scenario({
    id: 'procedure-cabg', title: 'Procedure-related MI · CABG context', learningObjective: 'Review simulated post-CABG evidence and timing.', descriptors: ['CABG context', 'Legacy 5 label'],
    evidence: [evidence('p5', 'PROCEDURE', 'PRESENT', at(8), 'Simulated CABG procedure context.'), evidence('t5', 'TROPONIN', 'PRESENT', at(10), 'Simulated post-procedure biomarker increase.'), evidence('i5', 'IMAGING', 'PRESENT', at(11), 'Simulated new loss of viable myocardium.'), evidence('e5', 'ECG', 'PRESENT', at(10), 'Simulated new pathological Q waves.')],
    timeline: [event('ev15', 8, 'PROCEDURE', 'CABG recorded', 'Procedure context begins timeline.', ['p5']), event('ev16', 10, 'TROPONIN', 'Post-procedure biomarker', 'Increase recorded.', ['t5']), event('ev17', 11, 'IMAGING', 'Imaging evidence', 'New simulated viability finding.', ['i5'])],
    troponinSeries: [{ occurredAt: at(8), value: 13, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(10), value: 145, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(12), value: 290, unit: 'ng/L', upperReferenceLimit: 14 }],
    expectedAssessment: { category: 'PROCEDURE_RELATED', legacyType: 'TYPE_5', presentation: 'UNKNOWN', label: 'Procedure-related MI pattern', confidence: 'SUPPORTED', explanation: 'The simulated procedure timing and evidence are presented together for review.', supportingEvidenceIds: ['p5', 't5', 'i5', 'e5'], conflictingEvidenceIds: [], evidenceGaps: [], disclaimer: 'SIMULATION_ONLY' },
  }),
  scenario({
    id: 'procedure-stent-thrombosis', title: 'Procedure-related MI · Stent thrombosis', learningObjective: 'Explore the legacy 4b descriptor with a simulated stent-thrombosis finding.', descriptors: ['PCI history', 'Legacy 4b label'],
    evidence: [evidence('p4b', 'PROCEDURE', 'PRESENT', at(8), 'Prior simulated PCI and stent context.'), evidence('a4b', 'ANGIOGRAPHY', 'PRESENT', at(9), 'Simulated coronary stent thrombosis finding.'), evidence('e4b', 'ECG', 'PRESENT', at(9), 'Simulated new ischaemic ECG change.'), evidence('t4b', 'TROPONIN', 'PRESENT', at(10), 'Simulated dynamic troponin rise.')],
    timeline: [event('ev4b1', 8, 'PROCEDURE', 'Prior PCI context', 'Stent history is present in the simulation.', ['p4b']), event('ev4b2', 9, 'ANGIOGRAPHY', 'Coronary finding', 'Stent thrombosis finding recorded.', ['a4b']), event('ev4b3', 10, 'TROPONIN', 'Serial biomarker', 'Rise recorded.', ['t4b'])],
    troponinSeries: [{ occurredAt: at(8), value: 10, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(10), value: 124, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(11), value: 268, unit: 'ng/L', upperReferenceLimit: 14 }],
    expectedAssessment: { category: 'PROCEDURE_RELATED', legacyType: 'TYPE_4B', presentation: 'NSTEMI', label: 'Procedure-related MI pattern', confidence: 'SUPPORTED', explanation: 'The simulation connects new injury evidence to a stent-thrombosis finding.', supportingEvidenceIds: ['p4b', 'a4b', 'e4b', 't4b'], conflictingEvidenceIds: [], evidenceGaps: [], disclaimer: 'SIMULATION_ONLY' },
  }),
  scenario({
    id: 'procedure-stent-restenosis', title: 'Procedure-related MI · Stent restenosis', learningObjective: 'Explore the legacy 4c descriptor with a simulated restenosis finding.', descriptors: ['PCI history', 'Legacy 4c label'],
    evidence: [evidence('p4c', 'PROCEDURE', 'PRESENT', at(8), 'Prior simulated PCI and stent context.'), evidence('a4c', 'ANGIOGRAPHY', 'PRESENT', at(9), 'Simulated in-stent restenosis finding.'), evidence('e4c', 'ECG', 'PRESENT', at(9), 'Simulated ischaemic ECG change.'), evidence('t4c', 'TROPONIN', 'PRESENT', at(10), 'Simulated dynamic troponin rise.')],
    timeline: [event('ev4c1', 8, 'PROCEDURE', 'Prior PCI context', 'Stent history is present in the simulation.', ['p4c']), event('ev4c2', 9, 'ANGIOGRAPHY', 'Coronary finding', 'Restenosis finding recorded.', ['a4c']), event('ev4c3', 10, 'TROPONIN', 'Serial biomarker', 'Rise recorded.', ['t4c'])],
    troponinSeries: [{ occurredAt: at(8), value: 13, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(10), value: 74, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(11), value: 166, unit: 'ng/L', upperReferenceLimit: 14 }],
    expectedAssessment: { category: 'PROCEDURE_RELATED', legacyType: 'TYPE_4C', presentation: 'NSTEMI', label: 'Procedure-related MI pattern', confidence: 'SUPPORTED', explanation: 'The simulation connects injury evidence to an in-stent restenosis finding.', supportingEvidenceIds: ['p4c', 'a4c', 'e4c', 't4c'], conflictingEvidenceIds: [], evidenceGaps: [], disclaimer: 'SIMULATION_ONLY' },
  }),
  scenario({
    id: 'type-3-pre-biomarker', title: 'Primary MI · Pre-biomarker event', learningObjective: 'Explore the legacy Type 3 descriptor when biomarker evidence is unavailable in the simulated timeline.', descriptors: ['Pre-biomarker evidence unavailable', 'Legacy 3 label'],
    evidence: [evidence('s3', 'SYMPTOMS', 'PRESENT', at(8), 'Simulated acute ischaemic symptoms.'), evidence('e3b', 'ECG', 'PRESENT', at(8, 5), 'Simulated presumed new ischaemic ECG changes with ventricular arrhythmia.'), evidence('t3b', 'TROPONIN', 'NOT_OBSERVED', at(8, 20), 'No simulated biomarker sample is available before the event.', ['This scenario intentionally contains no serial biomarker data.'])],
    timeline: [event('ev3a', 8, 'SYMPTOMS', 'Symptoms recorded', 'Simulated acute onset.', ['s3']), event('ev3b', 8, 'ECG', 'ECG evidence', 'Presumed new ischaemic change and arrhythmia recorded.', ['e3b']), event('ev3c', 8, 'TROPONIN', 'Biomarker unavailable', 'No specimen precedes the simulated event.', ['t3b'])],
    troponinSeries: [],
    expectedAssessment: { category: 'PRIMARY', legacyType: 'TYPE_3', presentation: 'UNKNOWN', label: 'Primary MI pattern', confidence: 'POSSIBLE', explanation: 'This simulation demonstrates the legacy Type 3 descriptor with explicitly unavailable biomarker evidence.', supportingEvidenceIds: ['s3', 'e3b'], conflictingEvidenceIds: [], evidenceGaps: ['No simulated cardiac troponin value is available before the event.'], disclaimer: 'SIMULATION_ONLY' },
  }),
  scenario({
    id: 'injury-not-mi', title: 'Acute myocardial injury · Not MI', learningObjective: 'See why elevated troponin alone does not establish an MI pattern.', descriptors: ['Renal dysfunction context', 'No simulated ischaemia evidence'],
    evidence: [evidence('t6', 'TROPONIN', 'PRESENT', at(9), 'Simulated elevated troponin with small dynamic change.'), evidence('e6', 'ECG', 'ABSENT', at(9), 'No simulated new ischaemic ECG change.'), evidence('s6', 'SYMPTOMS', 'ABSENT', at(9), 'No simulated ischaemic symptoms.'), evidence('i6', 'IMAGING', 'ABSENT', at(10), 'No simulated new ischaemic imaging finding.'), evidence('c6', 'CONTEXT', 'PRESENT', at(8), 'Simulated chronic kidney disease context.')],
    timeline: [event('ev18', 8, 'CONTEXT', 'Context recorded', 'Non-ischaemic context documented.', ['c6']), event('ev19', 9, 'TROPONIN', 'Biomarker observed', 'Elevation is visible without ischaemia evidence.', ['t6']), event('ev20', 10, 'IMAGING', 'Imaging review', 'No new simulated regional finding.', ['i6'])],
    troponinSeries: [{ occurredAt: at(8), value: 44, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(9), value: 52, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(10), value: 48, unit: 'ng/L', upperReferenceLimit: 14 }],
    expectedAssessment: { category: 'NON_ISCHAEMIC_INJURY', presentation: 'UNKNOWN', label: 'Myocardial injury pattern', confidence: 'SUPPORTED', explanation: 'The simulation shows injury evidence but no supporting acute ischaemia evidence.', supportingEvidenceIds: ['t6', 'e6', 's6', 'i6', 'c6'], conflictingEvidenceIds: [], evidenceGaps: [], disclaimer: 'SIMULATION_ONLY' },
  }),
  scenario({
    id: 'unresolved-minoca', title: 'Unresolved pattern · Non-obstructive coronaries', learningObjective: 'Keep a working diagnosis unresolved when the simulated cause is not established.', descriptors: ['Non-obstructive coronaries', 'Working diagnosis only'],
    evidence: [evidence('s7', 'SYMPTOMS', 'PRESENT', at(8), 'Simulated ischaemic symptoms.'), evidence('t7', 'TROPONIN', 'PRESENT', at(9), 'Simulated dynamic biomarker rise.'), evidence('a7', 'ANGIOGRAPHY', 'PRESENT', at(10), 'Non-obstructive coronary finding in scenario.'), evidence('i7', 'IMAGING', 'INDETERMINATE', at(11), 'Mechanism not established in this scenario.', ['Further simulated workup intentionally withheld.'])],
    timeline: [event('ev21', 8, 'SYMPTOMS', 'Symptoms recorded', 'Simulated onset.', ['s7']), event('ev22', 9, 'TROPONIN', 'Serial biomarker', 'Rise recorded.', ['t7']), event('ev23', 10, 'ANGIOGRAPHY', 'Coronary context', 'Non-obstructive finding recorded.', ['a7'])],
    troponinSeries: [{ occurredAt: at(8), value: 12, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(9), value: 87, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(10), value: 155, unit: 'ng/L', upperReferenceLimit: 14 }],
    expectedAssessment: { category: 'UNRESOLVED', presentation: 'NSTEMI', label: 'Unresolved working pattern', confidence: 'INSUFFICIENT_EVIDENCE', explanation: 'The simulation intentionally withholds mechanism-defining evidence.', supportingEvidenceIds: ['s7', 't7', 'a7'], conflictingEvidenceIds: [], evidenceGaps: ['Underlying mechanism remains unestablished.'], disclaimer: 'SIMULATION_ONLY' },
  }),
  scenario({
    id: 'silent-recurrent', title: 'Primary MI · Silent recurrent presentation', learningObjective: 'Explore a simulated recurrent event without reported symptoms.', descriptors: ['Prior event context', 'Silent presentation'],
    evidence: [evidence('s8', 'SYMPTOMS', 'ABSENT', at(8), 'No simulated symptoms reported.'), evidence('t8', 'TROPONIN', 'PRESENT', at(9), 'Simulated dynamic biomarker rise.'), evidence('e8', 'ECG', 'PRESENT', at(9), 'Simulated new ischaemic changes.'), evidence('i8', 'IMAGING', 'PRESENT', at(10), 'Simulated new regional wall-motion abnormality.'), evidence('a8', 'ANGIOGRAPHY', 'PRESENT', at(11), 'Simulated acute coronary pathology.')],
    timeline: [event('ev24', 8, 'CONTEXT', 'Prior event context', 'Recurrent-event history is simulated.', []), event('ev25', 9, 'TROPONIN', 'Serial biomarker', 'Rise recorded.', ['t8']), event('ev26', 9, 'ECG', 'ECG evidence', 'New simulated change recorded.', ['e8']), event('ev27', 11, 'ANGIOGRAPHY', 'Coronary context', 'Acute pathology recorded.', ['a8'])],
    troponinSeries: [{ occurredAt: at(8), value: 16, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(9), value: 98, unit: 'ng/L', upperReferenceLimit: 14 }, { occurredAt: at(11), value: 370, unit: 'ng/L', upperReferenceLimit: 14 }],
    expectedAssessment: { category: 'PRIMARY', legacyType: 'TYPE_1', presentation: 'SILENT_OR_UNRECOGNIZED', label: 'Primary MI pattern', confidence: 'SUPPORTED', explanation: 'The simulated pattern is supported despite absent reported symptoms.', supportingEvidenceIds: ['s8', 't8', 'e8', 'i8', 'a8'], conflictingEvidenceIds: [], evidenceGaps: [], disclaimer: 'SIMULATION_ONLY' },
  }),
];

export const getMiScenario = (id: string): MiScenarioCase => miScenarios.find((item) => item.id === id) ?? miScenarios[0];
export const getMiScenarioGroups = (): readonly MiClinicalGroup[] => ['PRIMARY', 'SECONDARY', 'PROCEDURE_RELATED', 'NON_ISCHAEMIC_INJURY', 'UNRESOLVED'];
