import React, { ReactNode } from 'react';
import { ClipboardList, FileText, History, ShieldCheck, Sparkles } from 'lucide-react';

export const ReviewWorkspace: React.FC<{ snapshotsCount: number; onOpenSnapshots: () => void; onOpenAudit: () => void; onOpenReport: () => void; onOpenPrediction: () => void; children: ReactNode }> = ({ snapshotsCount, onOpenSnapshots, onOpenAudit, onOpenReport, onOpenPrediction, children }) => (
  <div className="space-y-4">
    <section className="rounded-2xl border border-slate-800 bg-slate-900/65 p-4 sm:p-5"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Review workspace</p><h2 className="mt-1 text-base font-semibold text-white">Understand what changed, then document the decision</h2><p className="mt-1 text-xs text-slate-400">Live controls are deliberately absent here; this is the place for trends, comparisons, exports, and audit review.</p></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><button onClick={onOpenSnapshots} className="rounded-xl border border-slate-800 bg-slate-950/70 p-3 text-left hover:border-teal-500/40"><History className="h-4 w-4 text-teal-300" /><div className="mt-2 text-xs font-semibold text-slate-100">Snapshots</div><div className="mt-1 text-[11px] text-slate-500">{snapshotsCount} saved</div></button><button onClick={onOpenReport} className="rounded-xl border border-slate-800 bg-slate-950/70 p-3 text-left hover:border-teal-500/40"><FileText className="h-4 w-4 text-sky-300" /><div className="mt-2 text-xs font-semibold text-slate-100">Report</div><div className="mt-1 text-[11px] text-slate-500">Prepare export</div></button><button onClick={onOpenAudit} className="rounded-xl border border-slate-800 bg-slate-950/70 p-3 text-left hover:border-teal-500/40"><ShieldCheck className="h-4 w-4 text-emerald-300" /><div className="mt-2 text-xs font-semibold text-slate-100">Audit trail</div><div className="mt-1 text-[11px] text-slate-500">Review activity</div></button><button onClick={onOpenPrediction} className="rounded-xl border border-slate-800 bg-slate-950/70 p-3 text-left hover:border-teal-500/40"><Sparkles className="h-4 w-4 text-amber-300" /><div className="mt-2 text-xs font-semibold text-slate-100">Projection</div><div className="mt-1 text-[11px] text-slate-500">Explore trend</div></button></div></section>
    <section className="rounded-xl border border-slate-800 bg-slate-900/40 p-3 text-xs text-slate-400"><span className="inline-flex items-center gap-2"><ClipboardList className="h-4 w-4 text-teal-300" />Use source-linked review artifacts; do not treat simulated trends as diagnostic evidence.</span></section>
    {children}
  </div>
);
